server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shopping_store
    username: commerce
    password: commerce
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
