server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/shopping_cart
    username: commerce
    password: commerce
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
