server:
  port: 8080

spring:
  application:
    name: collector

collector:
  kafka:
    bootstrap-servers: localhost:9092
    sensor-events-topic: telemetry.sensors.v1
    hub-events-topic: telemetry.hubs.v1

logging:
  level:
    ru.yandex.practicum.telemetry.collector: INFO
