spring:
  application:
    name: analyzer
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer
    username: analyzer
    password: analyzer
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always

analyzer:
  kafka:
    bootstrap-servers: localhost:9092
    hub-events-topic: telemetry.hubs.v1
    snapshots-topic: telemetry.snapshots.v1
    hub-consumer:
      group-id: telemetry.analyzer.hubs
      auto-offset-reset: earliest
      max-poll-records: 50
      poll-timeout-ms: 1000
    snapshot-consumer:
      group-id: telemetry.analyzer.snapshots
      auto-offset-reset: earliest
      max-poll-records: 1
      poll-timeout-ms: 1000

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.yandex.practicum.telemetry.analyzer: INFO
